set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# --- Toolchain path handling ---
if(DEFINED ENV{TOOLCHAIN_FOLDER})
    set(TOOLCHAIN_FOLDER "$ENV{TOOLCHAIN_FOLDER}")
    message(STATUS "Using TOOLCHAIN_FOLDER from environment: ${TOOLCHAIN_FOLDER}")
else()
    set(TOOLCHAIN_FOLDER "f:/MounRiver/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/RISC-V Embedded GCC15")
endif()

set(TOOLCHAIN_PREFIX "riscv32-wch-elf-")

# --- Host executable suffix ---
if(CMAKE_HOST_WIN32)
    set(EXE_EXT ".exe")
else()
    set(EXE_EXT "")
endif()

set(CMAKE_C_COMPILER   "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}gcc${EXE_EXT}" CACHE FILEPATH "RISC-V C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}g++${EXE_EXT}" CACHE FILEPATH "RISC-V C++ compiler" FORCE)
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}gcc${EXE_EXT}" CACHE FILEPATH "RISC-V ASM compiler" FORCE)
set(CMAKE_OBJCOPY      "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}objcopy${EXE_EXT}" CACHE FILEPATH "RISC-V objcopy" FORCE)
set(CMAKE_OBJDUMP      "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}objdump${EXE_EXT}" CACHE FILEPATH "RISC-V objdump" FORCE)
set(CMAKE_SIZE         "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}size${EXE_EXT}" CACHE FILEPATH "RISC-V size" FORCE)
set(CMAKE_AR           "${TOOLCHAIN_FOLDER}/bin/${TOOLCHAIN_PREFIX}ar${EXE_EXT}" CACHE FILEPATH "RISC-V ar" FORCE)

if(NOT EXISTS "${CMAKE_C_COMPILER}")
    message(FATAL_ERROR "RISC-V C compiler not found: ${CMAKE_C_COMPILER}")
endif()
if(NOT EXISTS "${CMAKE_CXX_COMPILER}")
    message(FATAL_ERROR "RISC-V C++ compiler not found: ${CMAKE_CXX_COMPILER}")
endif()
if(NOT EXISTS "${CMAKE_ASM_COMPILER}")
    message(FATAL_ERROR "RISC-V ASM compiler not found: ${CMAKE_ASM_COMPILER}")
endif()
if(NOT EXISTS "${CMAKE_OBJCOPY}")
    message(FATAL_ERROR "RISC-V objcopy not found: ${CMAKE_OBJCOPY}")
endif()
if(NOT EXISTS "${CMAKE_OBJDUMP}")
    message(FATAL_ERROR "RISC-V objdump not found: ${CMAKE_OBJDUMP}")
endif()
if(NOT EXISTS "${CMAKE_SIZE}")
    message(FATAL_ERROR "RISC-V size not found: ${CMAKE_SIZE}")
endif()
if(NOT EXISTS "${CMAKE_AR}")
    message(FATAL_ERROR "RISC-V ar not found: ${CMAKE_AR}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
